### ISSUE TITLE
ROS plugins are broken

### ISSUE THREAD

**Issue by kartikmohta** [facontidavide/PlotJuggler#20]
Looks like when removing the boost dependency in 1c001e05b625e4d5d382b077e992e98cf3fd91d6, the ROS plugins were not updated.

**Comment by facontidavide** [comment]
sorry about that.

It compiles now, but unfortunately I am not able to check right now if it actually works at runtime, since I am working on a Windows PC.

I also include catkin_make and ROS indigo in the Travis CI to avoid these embarassing situations.

I will check the plugins on Monday, though. I will close this issue afterwards

**Comment by kartikmohta** [comment]
The fix works, thanks for fixing it quickly! 🙂
