### ISSUE TITLE
cannot creat folder at `home`

### ISSUE THREAD

**Issue by lianghongzhuo** [facontidavide/PlotJuggler#296]
Hi,
In our system, ` /home` folder is blocked by the file system manager to mount remote users. 
So when we install plotjuggler by the command `sudo apt install ros-XX-plotjuggler`, we will get an error:
```
 error creating directory './home/buildfarm': Permission denied
```
Could you put the `buildfarm` somewhere else?
For example, our typical home folder is located at `/homeL`
So by detecting the `$HOME` value, one can know where to create the `buildfarm` folder.
Thank you.

**Comment by v4hn** [comment]
No system binary is supposed to install any files in `/home` or any `$HOME` for that matter.
This is clearly a bug in the released packages due to short comings in handling the icon and desktop files [which I complained about before](https://github.com/facontidavide/PlotJuggler/commit/e8784fffadf9c6a087d46477b8e56a269de613d1#r38730664).

@facontidavide Please disable the logic for buildfarm builds. As this is still not standard-conform, I would propose to drop it again altogether, possibly providing the files for users to copy on their own if they want them around.

**Comment by facontidavide** [comment]
Yes I will just drop this altogether
