### ISSUE TITLE
PlotJuggler not building for Noetic

### ISSUE THREAD

**Issue by jakebonney10** [facontidavide/PlotJuggler#302]
I attempted to install plotjuggler as it is described on the source readme however the apt failed to locate the package. There is ros-noetic-plotjuggler-msg but no ros-noetic-plotjuggler.

My terminal output...

`username@pc:~$ sudo apt-get install ros-noetic-plotjuggler`
`Reading package lists... Done`
`Building dependency tree`  
`Reading state information... Done`
`E: Unable to locate package ros-noetic-plotjuggler`

**Comment by doisyg** [comment]
It is not a building issue, it is because the package is not released yet for noetic (i am sure it would build fine  if you tried compilng from source). It seems Davide actually released it https://github.com/facontidavide/plotjuggler-release, so it will appear when there will be the next repo update.
