### ISSUE TITLE
White font on white background is difficult to read

### ISSUE THREAD

**Issue by romainreignier** [facontidavide/PlotJuggler#360]
Hi @facontidavide and thank you for this new Plotjuggler 3.0.

I was amazed to see that it has already reached OpenRobotics repos and is already installed in my system, just after the post on Discourse!

In the *Streaming* panel the choices in the combobox appear with a white font on white background when hovered on my system which makes the one hovered unreadable.
I use Kubuntu (KDE) 18.04 without any fancy theme, just the default one.

See:
![ksnip_20201210-173818](https://user-images.githubusercontent.com/8845664/101801515-b8be6b00-3b0e-11eb-8f95-b0705314b8b5.png)

I have tried the version 3.0.2 from the repos and 3.0.4 from `main` branch (you should change the branch name in the issue template, it stills uses `master` wording).

**Comment by facontidavide** [comment]
That is weird and, as you may imagine, this is not what happens on my computer ;) 

This is probably due to some specific theme settings in your Kubuntu  that need to be overridden.

Since I can not replicate this on my side, I need your help to fix it.

[stylesheet_light.zip](https://github.com/facontidavide/PlotJuggler/files/5674452/stylesheet_light.zip)

Download and uncompress this file.

Try to load it with the command **Tools->Load Stylesheet** and tell me if it solves the issue.

**Comment by facontidavide** [comment]
I am confident it is ok now

**Comment by romainreignier** [comment]
Indeed, it works now, I can see the labels.
But there is not effect on hovering. I don't know if it is desired.

**Comment by facontidavide** [comment]
no, it is not derired :(

**Comment by facontidavide** [comment]
I am closing this. Let me know if with the latest version the problem persists.
