### ISSUE TITLE
PJ seems not plot well for high frequency data ~ 200Hz

### ISSUE THREAD

**Issue by extr15** [facontidavide/PlotJuggler#576]
Thanks for your great tool, it helps a lot!

# Problem description

When play a rosbag and plot the timestamp of a 200Hz data, it seems PJ plots not right (the red one, I have another 50Hz data, the green one as a comparison). The timestamp increase 5ms for each data, thus the plot should be a line, while it not:
![image](https://user-images.githubusercontent.com/19777236/147534836-c89e06ff-f646-4277-b577-e2363244600d.png)
If I play rosbag with `-r 0.5`( play rate * 0.5), the plot seems better but still not right:
![image](https://user-images.githubusercontent.com/19777236/147535204-7c07775e-8800-451a-9eb2-dc8ed46f39f5.png)
Instead if I load the rosbag to PJ directly and plot the timestamp, it is right(the two data coincide):
![image](https://user-images.githubusercontent.com/19777236/147534927-5a875466-08ce-4089-a46b-26cecb2daa69.png)
My system is `Linux 5.11.0-43-generic #47~20.04.2-Ubuntu`.
Thanks.

**Comment by facontidavide** [comment]
My educated guess is that this is related to TCp transport https://en.wikipedia.org/wiki/Nagle%27s_algorithm

Unlerss you specify "use the timestamp from header.stamp", the timestamp used will be based on when PlotJuggler "received" the message and, because of the Nagle algorithm, messages at this frequency are sent in "batches".

**Comment by extr15** [comment]
@facontidavide , Thanks for the reply and it makes sense.
Does PJ support "use the timestamp from header.stamp"?
